(define (problem rapid-instance-26)
        (:domain rapid)
        
    (:objects
        safe0 safe1 - safe-location
        affected0 affected1 affected2 affected3 affected4 affected5 affected6 - affected-location
        medics0 medics1 medics2 - medical-support-team
        rescuers0 rescuers1 rescuers2 - rescue-team
        truck0 truck1 truck2 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe1)
        (at truck1 safe1)
        (at truck2 safe0)
        (at bus0 safe0)
        (at bus1 safe0)
        (at medics0 safe1)
        (at medics1 safe0)
        (at medics2 safe1)
        (at rescuers0 safe0)
        (at rescuers1 safe1)
        (at rescuers2 safe0)
        (needs-rescue affected4)
        (needs-rescue affected1)
        (needs-rescue affected6)
        (needs-rescue affected5)
        (needs-rescue affected2)
        (needs-rescue affected0)
        (needs-rescue affected3)
        (needs-medical-support affected2)
        (needs-medical-support affected5)
        (needs-medical-support affected4)
        (needs-medical-support affected0)
        (needs-medical-support affected1)
        (needs-medical-support affected3)
        (needs-evacuation affected6)
        (needs-evacuation affected0)
        (needs-evacuation affected1)
        (needs-evacuation affected3)
        (needs-evacuation affected5)
        (= (person-to-evacuate affected6) 20)
        (= (person-to-evacuate affected0) 40)
        (= (person-to-evacuate affected1) 140)
        (= (person-to-evacuate affected3) 150)
        (= (person-to-evacuate affected5) 80)
        (= (priority affected0) 13)
        (= (priority affected1) 5)
        (= (priority affected2) 4)
        (= (priority affected3) 9)
        (= (priority affected4) 2)
        (= (priority affected5) 10)
        (= (priority affected6) 6)
        (= (team-size medics0) 20)
        (= (team-size medics1) 10)
        (= (team-size medics2) 15)
        (= (team-size rescuers0) 25)
        (= (team-size rescuers1) 25)
        (= (team-size rescuers2) 20)
        (= (stock safe0 medicine) 4900)
        (= (stock safe0 food) 700)
        (= (stock safe0 water) 1400)
        (= (stock safe1 medicine) 6300)
        (= (stock safe1 food) 6300)
        (= (stock safe1 water) 4900)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (stock affected2 medicine) 0)
        (= (stock affected2 food) 0)
        (= (stock affected2 water) 0)
        (= (stock affected3 medicine) 0)
        (= (stock affected3 food) 0)
        (= (stock affected3 water) 0)
        (= (stock affected4 medicine) 0)
        (= (stock affected4 food) 0)
        (= (stock affected4 water) 0)
        (= (stock affected5 medicine) 0)
        (= (stock affected5 food) 0)
        (= (stock affected5 water) 0)
        (= (stock affected6 medicine) 0)
        (= (stock affected6 food) 0)
        (= (stock affected6 water) 0)
        (= (needs-resource affected0 medicine) 0)
        (= (needs-resource affected0 food) 0)
        (= (needs-resource affected0 water) 90)
        (= (needs-resource affected1 medicine) 0)
        (= (needs-resource affected1 food) 60)
        (= (needs-resource affected1 water) 0)
        (= (needs-resource affected2 medicine) 50)
        (= (needs-resource affected2 food) 100)
        (= (needs-resource affected2 water) 100)
        (= (needs-resource affected3 medicine) 30)
        (= (needs-resource affected3 food) 50)
        (= (needs-resource affected3 water) 60)
        (= (needs-resource affected4 medicine) 20)
        (= (needs-resource affected4 food) 10)
        (= (needs-resource affected4 water) 90)
        (= (needs-resource affected5 medicine) 60)
        (= (needs-resource affected5 food) 60)
        (= (needs-resource affected5 water) 90)
        (= (needs-resource affected6 medicine) 70)
        (= (needs-resource affected6 food) 100)
        (= (needs-resource affected6 water) 60)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus0 affected2) 0)
        (= (evacuating bus0 affected3) 0)
        (= (evacuating bus0 affected4) 0)
        (= (evacuating bus0 affected5) 0)
        (= (evacuating bus0 affected6) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (evacuating bus1 affected2) 0)
        (= (evacuating bus1 affected3) 0)
        (= (evacuating bus1 affected4) 0)
        (= (evacuating bus1 affected5) 0)
        (= (evacuating bus1 affected6) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (contains truck2 medicine) 0)
        (= (contains truck2 food) 0)
        (= (contains truck2 water) 0)
        (= (capacity bus0) 70)
        (= (capacity bus1) 90)
        (= (capacity truck0) 50)
        (= (capacity truck1) 250)
        (= (capacity truck2) 200)
        (= (distance safe0 safe1) 270)
        (= (distance safe1 safe0) 270)
        (= (distance safe0 affected0) 340)
        (= (distance affected0 safe0) 340)
        (= (distance safe0 affected1) 200)
        (= (distance affected1 safe0) 200)
        (= (distance safe0 affected2) 100)
        (= (distance affected2 safe0) 100)
        (= (distance safe0 affected3) 190)
        (= (distance affected3 safe0) 190)
        (= (distance safe0 affected4) 190)
        (= (distance affected4 safe0) 190)
        (= (distance safe0 affected5) 340)
        (= (distance affected5 safe0) 340)
        (= (distance safe0 affected6) 150)
        (= (distance affected6 safe0) 150)
        (= (distance safe1 affected0) 50)
        (= (distance affected0 safe1) 50)
        (= (distance safe1 affected1) 40)
        (= (distance affected1 safe1) 40)
        (= (distance safe1 affected2) 20)
        (= (distance affected2 safe1) 20)
        (= (distance safe1 affected3) 190)
        (= (distance affected3 safe1) 190)
        (= (distance safe1 affected4) 190)
        (= (distance affected4 safe1) 190)
        (= (distance safe1 affected5) 360)
        (= (distance affected5 safe1) 360)
        (= (distance safe1 affected6) 20)
        (= (distance affected6 safe1) 20)
        (= (distance affected0 affected1) 240)
        (= (distance affected1 affected0) 240)
        (= (distance affected0 affected2) 490)
        (= (distance affected2 affected0) 490)
        (= (distance affected0 affected3) 220)
        (= (distance affected3 affected0) 220)
        (= (distance affected0 affected4) 450)
        (= (distance affected4 affected0) 450)
        (= (distance affected0 affected5) 500)
        (= (distance affected5 affected0) 500)
        (= (distance affected0 affected6) 310)
        (= (distance affected6 affected0) 310)
        (= (distance affected1 affected2) 130)
        (= (distance affected2 affected1) 130)
        (= (distance affected1 affected3) 100)
        (= (distance affected3 affected1) 100)
        (= (distance affected1 affected4) 420)
        (= (distance affected4 affected1) 420)
        (= (distance affected1 affected5) 340)
        (= (distance affected5 affected1) 340)
        (= (distance affected1 affected6) 130)
        (= (distance affected6 affected1) 130)
        (= (distance affected2 affected3) 480)
        (= (distance affected3 affected2) 480)
        (= (distance affected2 affected4) 310)
        (= (distance affected4 affected2) 310)
        (= (distance affected2 affected5) 70)
        (= (distance affected5 affected2) 70)
        (= (distance affected2 affected6) 120)
        (= (distance affected6 affected2) 120)
        (= (distance affected3 affected4) 320)
        (= (distance affected4 affected3) 320)
        (= (distance affected3 affected5) 150)
        (= (distance affected5 affected3) 150)
        (= (distance affected3 affected6) 290)
        (= (distance affected6 affected3) 290)
        (= (distance affected4 affected5) 320)
        (= (distance affected5 affected4) 320)
        (= (distance affected4 affected6) 60)
        (= (distance affected6 affected4) 60)
        (= (distance affected5 affected6) 80)
        (= (distance affected6 affected5) 80)
        (= (per-unit-distance-cost bus0) 20)
        (= (per-unit-distance-cost bus1) 30)
        (= (per-unit-distance-cost truck0) 30)
        (= (per-unit-distance-cost truck1) 40)
        (= (per-unit-distance-cost truck2) 20)
        (= (per-unit-distance-time bus0) 1)
        (= (per-unit-distance-time bus1) 1)
        (= (per-unit-distance-time truck0) 2)
        (= (per-unit-distance-time truck1) 3)
        (= (per-unit-distance-time truck2) 2)
        (= (per-unit-distribution-cost medicine) 1)
        (= (per-unit-distribution-cost food) 7)
        (= (per-unit-distribution-cost water) 5)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected6))
            (not (needs-evacuation affected0))
            (not (needs-evacuation affected1))
            (not (needs-evacuation affected3))
            (not (needs-evacuation affected5))
            (not (needs-medical-support affected2))
            (not (needs-medical-support affected5))
            (not (needs-medical-support affected4))
            (not (needs-medical-support affected0))
            (not (needs-medical-support affected1))
            (not (needs-medical-support affected3))
            (not (needs-rescue affected4))
            (not (needs-rescue affected1))
            (not (needs-rescue affected6))
            (not (needs-rescue affected5))
            (not (needs-rescue affected2))
            (not (needs-rescue affected0))
            (not (needs-rescue affected3))
            (= (person-to-evacuate affected6) 0)
            (= (person-to-evacuate affected0) 0)
            (= (person-to-evacuate affected1) 0)
            (= (person-to-evacuate affected3) 0)
            (= (person-to-evacuate affected5) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (needs-resource affected2 medicine) 0)
            (= (needs-resource affected2 food) 0)
            (= (needs-resource affected2 water) 0)
            (= (needs-resource affected3 medicine) 0)
            (= (needs-resource affected3 food) 0)
            (= (needs-resource affected3 water) 0)
            (= (needs-resource affected4 medicine) 0)
            (= (needs-resource affected4 food) 0)
            (= (needs-resource affected4 water) 0)
            (= (needs-resource affected5 medicine) 0)
            (= (needs-resource affected5 food) 0)
            (= (needs-resource affected5 water) 0)
            (= (needs-resource affected6 medicine) 0)
            (= (needs-resource affected6 food) 0)
            (= (needs-resource affected6 water) 0)
            (= (capacity bus0) 70)
            (= (capacity bus1) 90)
            (= (capacity truck0) 50)
            (= (capacity truck1) 250)
            (= (capacity truck2) 200)
            (at truck0 safe1)
            (at truck1 safe1)
            (at truck2 safe0)
            (at bus0 safe0)
            (at bus1 safe0)
            (at medics0 safe1)
            (at medics1 safe0)
            (at medics2 safe1)
            (at rescuers0 safe0)
            (at rescuers1 safe1)
            (at rescuers2 safe0)
        )
    )
)
