(define (problem rapid-instance-16)
        (:domain rapid)
        
    (:objects
        safe0 safe1 - safe-location
        affected0 affected1 - affected-location
        medics0 medics1 - medical-support-team
        rescuers0 rescuers1 - rescue-team
        truck0 truck1 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe1)
        (at truck1 safe0)
        (at bus0 safe1)
        (at bus1 safe0)
        (at medics0 safe1)
        (at medics1 safe1)
        (at rescuers0 safe0)
        (at rescuers1 safe1)
        (needs-rescue affected0)
        (needs-medical-support affected0)
        (needs-evacuation affected0)
        (= (person-to-evacuate affected0) 50)
        (= (priority affected0) 2)
        (= (priority affected1) 3)
        (= (team-size medics0) 10)
        (= (team-size medics1) 20)
        (= (team-size rescuers0) 25)
        (= (team-size rescuers1) 20)
        (= (stock safe0 medicine) 1200)
        (= (stock safe0 food) 400)
        (= (stock safe0 water) 800)
        (= (stock safe1 medicine) 0)
        (= (stock safe1 food) 0)
        (= (stock safe1 water) 0)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (needs-resource affected0 medicine) 30)
        (= (needs-resource affected0 food) 70)
        (= (needs-resource affected0 water) 20)
        (= (needs-resource affected1 medicine) 50)
        (= (needs-resource affected1 food) 100)
        (= (needs-resource affected1 water) 70)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (capacity bus0) 70)
        (= (capacity bus1) 60)
        (= (capacity truck0) 150)
        (= (capacity truck1) 250)
        (= (distance safe0 safe1) 440)
        (= (distance safe1 safe0) 440)
        (= (distance safe0 affected0) 430)
        (= (distance affected0 safe0) 430)
        (= (distance safe0 affected1) 400)
        (= (distance affected1 safe0) 400)
        (= (distance safe1 affected0) 180)
        (= (distance affected0 safe1) 180)
        (= (distance safe1 affected1) 360)
        (= (distance affected1 safe1) 360)
        (= (distance affected0 affected1) 450)
        (= (distance affected1 affected0) 450)
        (= (per-unit-distance-cost bus0) 50)
        (= (per-unit-distance-cost bus1) 50)
        (= (per-unit-distance-cost truck0) 50)
        (= (per-unit-distance-cost truck1) 40)
        (= (per-unit-distance-time bus0) 6)
        (= (per-unit-distance-time bus1) 8)
        (= (per-unit-distance-time truck0) 6)
        (= (per-unit-distance-time truck1) 7)
        (= (per-unit-distribution-cost medicine) 10)
        (= (per-unit-distribution-cost food) 3)
        (= (per-unit-distribution-cost water) 6)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected0))
            (not (needs-medical-support affected0))
            (not (needs-rescue affected0))
            (= (person-to-evacuate affected0) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (capacity bus0) 70)
            (= (capacity bus1) 60)
            (= (capacity truck0) 150)
            (= (capacity truck1) 250)
            (at truck0 safe1)
            (at truck1 safe0)
            (at bus0 safe1)
            (at bus1 safe0)
            (at medics0 safe1)
            (at medics1 safe1)
            (at rescuers0 safe0)
            (at rescuers1 safe1)
        )
    )
)
