(define (problem rapid-instance-15)
        (:domain rapid)
        
    (:objects
        safe0 safe1 - safe-location
        affected0 affected1 - affected-location
        medics0 medics1 - medical-support-team
        rescuers0 rescuers1 - rescue-team
        truck0 truck1 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe1)
        (at bus0 safe1)
        (at bus1 safe0)
        (at medics0 safe1)
        (at medics1 safe1)
        (at rescuers0 safe0)
        (at rescuers1 safe1)
        (needs-rescue affected0)
        (needs-medical-support affected1)
        (needs-evacuation affected1)
        (= (person-to-evacuate affected1) 60)
        (= (priority affected0) 2)
        (= (priority affected1) 1)
        (= (team-size medics0) 15)
        (= (team-size medics1) 25)
        (= (team-size rescuers0) 20)
        (= (team-size rescuers1) 15)
        (= (stock safe0 medicine) 600)
        (= (stock safe0 food) 400)
        (= (stock safe0 water) 1200)
        (= (stock safe1 medicine) 0)
        (= (stock safe1 food) 0)
        (= (stock safe1 water) 0)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (needs-resource affected0 medicine) 100)
        (= (needs-resource affected0 food) 50)
        (= (needs-resource affected0 water) 0)
        (= (needs-resource affected1 medicine) 100)
        (= (needs-resource affected1 food) 10)
        (= (needs-resource affected1 water) 100)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (capacity bus0) 40)
        (= (capacity bus1) 80)
        (= (capacity truck0) 100)
        (= (capacity truck1) 200)
        (= (distance safe0 safe1) 150)
        (= (distance safe1 safe0) 150)
        (= (distance safe0 affected0) 360)
        (= (distance affected0 safe0) 360)
        (= (distance safe0 affected1) 440)
        (= (distance affected1 safe0) 440)
        (= (distance safe1 affected0) 410)
        (= (distance affected0 safe1) 410)
        (= (distance safe1 affected1) 260)
        (= (distance affected1 safe1) 260)
        (= (distance affected0 affected1) 160)
        (= (distance affected1 affected0) 160)
        (= (per-unit-distance-cost bus0) 40)
        (= (per-unit-distance-cost bus1) 50)
        (= (per-unit-distance-cost truck0) 50)
        (= (per-unit-distance-cost truck1) 50)
        (= (per-unit-distance-time bus0) 10)
        (= (per-unit-distance-time bus1) 9)
        (= (per-unit-distance-time truck0) 8)
        (= (per-unit-distance-time truck1) 3)
        (= (per-unit-distribution-cost medicine) 7)
        (= (per-unit-distribution-cost food) 6)
        (= (per-unit-distribution-cost water) 8)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected1))
            (not (needs-medical-support affected1))
            (not (needs-rescue affected0))
            (= (person-to-evacuate affected1) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (capacity bus0) 40)
            (= (capacity bus1) 80)
            (= (capacity truck0) 100)
            (= (capacity truck1) 200)
            (at truck0 safe0)
            (at truck1 safe1)
            (at bus0 safe1)
            (at bus1 safe0)
            (at medics0 safe1)
            (at medics1 safe1)
            (at rescuers0 safe0)
            (at rescuers1 safe1)
        )
    )
)
