(define (problem rapid-instance-6)
        (:domain rapid)
        
    (:objects
        safe0 - safe-location
        affected0 affected1 - affected-location
        medics0 - medical-support-team
        rescuers0 - rescue-team
        truck0 truck1 - freight-vehicle
        bus0 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe0)
        (at bus0 safe0)
        (at medics0 safe0)
        (at rescuers0 safe0)
        (needs-rescue affected1)
        (needs-medical-support affected1)
        (needs-medical-support affected0)
        (needs-evacuation affected1)
        (needs-evacuation affected0)
        (= (person-to-evacuate affected1) 190)
        (= (person-to-evacuate affected0) 160)
        (= (priority affected0) 2)
        (= (priority affected1) 1)
        (= (team-size medics0) 10)
        (= (team-size rescuers0) 15)
        (= (stock safe0 medicine) 2000)
        (= (stock safe0 food) 800)
        (= (stock safe0 water) 800)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (needs-resource affected0 medicine) 100)
        (= (needs-resource affected0 food) 100)
        (= (needs-resource affected0 water) 60)
        (= (needs-resource affected1 medicine) 10)
        (= (needs-resource affected1 food) 20)
        (= (needs-resource affected1 water) 10)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (capacity bus0) 50)
        (= (capacity truck0) 200)
        (= (capacity truck1) 150)
        (= (distance safe0 affected0) 500)
        (= (distance affected0 safe0) 500)
        (= (distance safe0 affected1) 100)
        (= (distance affected1 safe0) 100)
        (= (distance affected0 affected1) 160)
        (= (distance affected1 affected0) 160)
        (= (per-unit-distance-cost bus0) 40)
        (= (per-unit-distance-cost truck0) 30)
        (= (per-unit-distance-cost truck1) 40)
        (= (per-unit-distance-time bus0) 4)
        (= (per-unit-distance-time truck0) 5)
        (= (per-unit-distance-time truck1) 3)
        (= (per-unit-distribution-cost medicine) 6)
        (= (per-unit-distribution-cost food) 7)
        (= (per-unit-distribution-cost water) 3)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected1))
            (not (needs-evacuation affected0))
            (not (needs-medical-support affected1))
            (not (needs-medical-support affected0))
            (not (needs-rescue affected1))
            (= (person-to-evacuate affected1) 0)
            (= (person-to-evacuate affected0) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (capacity bus0) 50)
            (= (capacity truck0) 200)
            (= (capacity truck1) 150)
            (at truck0 safe0)
            (at truck1 safe0)
            (at bus0 safe0)
            (at medics0 safe0)
            (at rescuers0 safe0)
        )
    )
)
