(define (problem rapid-instance-5)
        (:domain rapid)
        
    (:objects
        safe0 - safe-location
        affected0 affected1 - affected-location
        medics0 - medical-support-team
        rescuers0 - rescue-team
        truck0 truck1 - freight-vehicle
        bus0 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe0)
        (at bus0 safe0)
        (at medics0 safe0)
        (at rescuers0 safe0)
        (needs-rescue affected1)
        (needs-medical-support affected0)
        (needs-evacuation affected0)
        (needs-evacuation affected1)
        (= (person-to-evacuate affected0) 190)
        (= (person-to-evacuate affected1) 80)
        (= (priority affected0) 2)
        (= (priority affected1) 1)
        (= (team-size medics0) 25)
        (= (team-size rescuers0) 20)
        (= (stock safe0 medicine) 1200)
        (= (stock safe0 food) 1000)
        (= (stock safe0 water) 2000)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (needs-resource affected0 medicine) 10)
        (= (needs-resource affected0 food) 50)
        (= (needs-resource affected0 water) 60)
        (= (needs-resource affected1 medicine) 0)
        (= (needs-resource affected1 food) 40)
        (= (needs-resource affected1 water) 80)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (capacity bus0) 80)
        (= (capacity truck0) 100)
        (= (capacity truck1) 250)
        (= (distance safe0 affected0) 160)
        (= (distance affected0 safe0) 160)
        (= (distance safe0 affected1) 60)
        (= (distance affected1 safe0) 60)
        (= (distance affected0 affected1) 390)
        (= (distance affected1 affected0) 390)
        (= (per-unit-distance-cost bus0) 20)
        (= (per-unit-distance-cost truck0) 40)
        (= (per-unit-distance-cost truck1) 50)
        (= (per-unit-distance-time bus0) 4)
        (= (per-unit-distance-time truck0) 4)
        (= (per-unit-distance-time truck1) 6)
        (= (per-unit-distribution-cost medicine) 9)
        (= (per-unit-distribution-cost food) 6)
        (= (per-unit-distribution-cost water) 5)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected0))
            (not (needs-evacuation affected1))
            (not (needs-medical-support affected0))
            (not (needs-rescue affected1))
            (= (person-to-evacuate affected0) 0)
            (= (person-to-evacuate affected1) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (capacity bus0) 80)
            (= (capacity truck0) 100)
            (= (capacity truck1) 250)
            (at truck0 safe0)
            (at truck1 safe0)
            (at bus0 safe0)
            (at medics0 safe0)
            (at rescuers0 safe0)
        )
    )
)
