(define (problem rapid-instance-20)
        (:domain rapid)
        
    (:objects
        safe0 safe1 - safe-location
        affected0 affected1 affected2 - affected-location
        medics0 medics1 medics2 - medical-support-team
        rescuers0 rescuers1 rescuers2 - rescue-team
        truck0 truck1 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe1)
        (at bus0 safe0)
        (at bus1 safe1)
        (at medics0 safe0)
        (at medics1 safe0)
        (at medics2 safe0)
        (at rescuers0 safe1)
        (at rescuers1 safe0)
        (at rescuers2 safe1)
        (needs-rescue affected2)
        (needs-rescue affected1)
        (needs-medical-support affected1)
        (needs-evacuation affected1)
        (= (person-to-evacuate affected1) 180)
        (= (priority affected0) 5)
        (= (priority affected1) 4)
        (= (priority affected2) 1)
        (= (team-size medics0) 25)
        (= (team-size medics1) 15)
        (= (team-size medics2) 20)
        (= (team-size rescuers0) 10)
        (= (team-size rescuers1) 25)
        (= (team-size rescuers2) 10)
        (= (stock safe0 medicine) 1200)
        (= (stock safe0 food) 1800)
        (= (stock safe0 water) 0)
        (= (stock safe1 medicine) 3000)
        (= (stock safe1 food) 2400)
        (= (stock safe1 water) 1800)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (stock affected2 medicine) 0)
        (= (stock affected2 food) 0)
        (= (stock affected2 water) 0)
        (= (needs-resource affected0 medicine) 90)
        (= (needs-resource affected0 food) 60)
        (= (needs-resource affected0 water) 40)
        (= (needs-resource affected1 medicine) 30)
        (= (needs-resource affected1 food) 40)
        (= (needs-resource affected1 water) 10)
        (= (needs-resource affected2 medicine) 10)
        (= (needs-resource affected2 food) 70)
        (= (needs-resource affected2 water) 0)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus0 affected2) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (evacuating bus1 affected2) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (capacity bus0) 30)
        (= (capacity bus1) 20)
        (= (capacity truck0) 200)
        (= (capacity truck1) 100)
        (= (distance safe0 safe1) 100)
        (= (distance safe1 safe0) 100)
        (= (distance safe0 affected0) 30)
        (= (distance affected0 safe0) 30)
        (= (distance safe0 affected1) 140)
        (= (distance affected1 safe0) 140)
        (= (distance safe0 affected2) 20)
        (= (distance affected2 safe0) 20)
        (= (distance safe1 affected0) 420)
        (= (distance affected0 safe1) 420)
        (= (distance safe1 affected1) 440)
        (= (distance affected1 safe1) 440)
        (= (distance safe1 affected2) 460)
        (= (distance affected2 safe1) 460)
        (= (distance affected0 affected1) 230)
        (= (distance affected1 affected0) 230)
        (= (distance affected0 affected2) 110)
        (= (distance affected2 affected0) 110)
        (= (distance affected1 affected2) 320)
        (= (distance affected2 affected1) 320)
        (= (per-unit-distance-cost bus0) 40)
        (= (per-unit-distance-cost bus1) 40)
        (= (per-unit-distance-cost truck0) 50)
        (= (per-unit-distance-cost truck1) 30)
        (= (per-unit-distance-time bus0) 5)
        (= (per-unit-distance-time bus1) 3)
        (= (per-unit-distance-time truck0) 5)
        (= (per-unit-distance-time truck1) 5)
        (= (per-unit-distribution-cost medicine) 10)
        (= (per-unit-distribution-cost food) 5)
        (= (per-unit-distribution-cost water) 1)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected1))
            (not (needs-medical-support affected1))
            (not (needs-rescue affected2))
            (not (needs-rescue affected1))
            (= (person-to-evacuate affected1) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (needs-resource affected2 medicine) 0)
            (= (needs-resource affected2 food) 0)
            (= (needs-resource affected2 water) 0)
            (= (capacity bus0) 30)
            (= (capacity bus1) 20)
            (= (capacity truck0) 200)
            (= (capacity truck1) 100)
            (at truck0 safe0)
            (at truck1 safe1)
            (at bus0 safe0)
            (at bus1 safe1)
            (at medics0 safe0)
            (at medics1 safe0)
            (at medics2 safe0)
            (at rescuers0 safe1)
            (at rescuers1 safe0)
            (at rescuers2 safe1)
        )
    )
)
