(define (problem rapid-instance-10)
        (:domain rapid)
        
    (:objects
        safe0 - safe-location
        affected0 affected1 affected2 - affected-location
        medics0 medics1 - medical-support-team
        rescuers0 rescuers1 - rescue-team
        truck0 truck1 truck2 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe0)
        (at truck2 safe0)
        (at bus0 safe0)
        (at bus1 safe0)
        (at medics0 safe0)
        (at medics1 safe0)
        (at rescuers0 safe0)
        (at rescuers1 safe0)
        (needs-rescue affected2)
        (needs-rescue affected1)
        (needs-medical-support affected0)
        (needs-medical-support affected2)
        (needs-evacuation affected2)
        (= (person-to-evacuate affected2) 180)
        (= (priority affected0) 3)
        (= (priority affected1) 5)
        (= (priority affected2) 1)
        (= (team-size medics0) 10)
        (= (team-size medics1) 25)
        (= (team-size rescuers0) 15)
        (= (team-size rescuers1) 25)
        (= (stock safe0 medicine) 2700)
        (= (stock safe0 food) 900)
        (= (stock safe0 water) 1500)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (stock affected2 medicine) 0)
        (= (stock affected2 food) 0)
        (= (stock affected2 water) 0)
        (= (needs-resource affected0 medicine) 20)
        (= (needs-resource affected0 food) 60)
        (= (needs-resource affected0 water) 70)
        (= (needs-resource affected1 medicine) 50)
        (= (needs-resource affected1 food) 40)
        (= (needs-resource affected1 water) 50)
        (= (needs-resource affected2 medicine) 10)
        (= (needs-resource affected2 food) 10)
        (= (needs-resource affected2 water) 30)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus0 affected2) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (evacuating bus1 affected2) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (contains truck2 medicine) 0)
        (= (contains truck2 food) 0)
        (= (contains truck2 water) 0)
        (= (capacity bus0) 80)
        (= (capacity bus1) 90)
        (= (capacity truck0) 250)
        (= (capacity truck1) 50)
        (= (capacity truck2) 250)
        (= (distance safe0 affected0) 350)
        (= (distance affected0 safe0) 350)
        (= (distance safe0 affected1) 370)
        (= (distance affected1 safe0) 370)
        (= (distance safe0 affected2) 30)
        (= (distance affected2 safe0) 30)
        (= (distance affected0 affected1) 330)
        (= (distance affected1 affected0) 330)
        (= (distance affected0 affected2) 50)
        (= (distance affected2 affected0) 50)
        (= (distance affected1 affected2) 130)
        (= (distance affected2 affected1) 130)
        (= (per-unit-distance-cost bus0) 50)
        (= (per-unit-distance-cost bus1) 50)
        (= (per-unit-distance-cost truck0) 20)
        (= (per-unit-distance-cost truck1) 30)
        (= (per-unit-distance-cost truck2) 50)
        (= (per-unit-distance-time bus0) 4)
        (= (per-unit-distance-time bus1) 8)
        (= (per-unit-distance-time truck0) 4)
        (= (per-unit-distance-time truck1) 5)
        (= (per-unit-distance-time truck2) 10)
        (= (per-unit-distribution-cost medicine) 2)
        (= (per-unit-distribution-cost food) 3)
        (= (per-unit-distribution-cost water) 1)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected2))
            (not (needs-medical-support affected0))
            (not (needs-medical-support affected2))
            (not (needs-rescue affected2))
            (not (needs-rescue affected1))
            (= (person-to-evacuate affected2) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (needs-resource affected2 medicine) 0)
            (= (needs-resource affected2 food) 0)
            (= (needs-resource affected2 water) 0)
            (= (capacity bus0) 80)
            (= (capacity bus1) 90)
            (= (capacity truck0) 250)
            (= (capacity truck1) 50)
            (= (capacity truck2) 250)
            (at truck0 safe0)
            (at truck1 safe0)
            (at truck2 safe0)
            (at bus0 safe0)
            (at bus1 safe0)
            (at medics0 safe0)
            (at medics1 safe0)
            (at rescuers0 safe0)
            (at rescuers1 safe0)
        )
    )
)
