(define (problem rapid-instance-13)
        (:domain rapid)
        
    (:objects
        safe0 - safe-location
        affected0 affected1 affected2 - affected-location
        medics0 medics1 - medical-support-team
        rescuers0 rescuers1 - rescue-team
        truck0 truck1 truck2 - freight-vehicle
        bus0 bus1 bus2 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe0)
        (at truck2 safe0)
        (at bus0 safe0)
        (at bus1 safe0)
        (at bus2 safe0)
        (at medics0 safe0)
        (at medics1 safe0)
        (at rescuers0 safe0)
        (at rescuers1 safe0)
        (needs-rescue affected1)
        (needs-rescue affected2)
        (needs-rescue affected0)
        (needs-medical-support affected0)
        (needs-medical-support affected1)
        (needs-evacuation affected0)
        (needs-evacuation affected1)
        (needs-evacuation affected2)
        (= (person-to-evacuate affected0) 50)
        (= (person-to-evacuate affected1) 180)
        (= (person-to-evacuate affected2) 150)
        (= (priority affected0) 3)
        (= (priority affected1) 5)
        (= (priority affected2) 2)
        (= (team-size medics0) 25)
        (= (team-size medics1) 25)
        (= (team-size rescuers0) 25)
        (= (team-size rescuers1) 15)
        (= (stock safe0 medicine) 1800)
        (= (stock safe0 food) 900)
        (= (stock safe0 water) 3000)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (stock affected2 medicine) 0)
        (= (stock affected2 food) 0)
        (= (stock affected2 water) 0)
        (= (needs-resource affected0 medicine) 90)
        (= (needs-resource affected0 food) 100)
        (= (needs-resource affected0 water) 20)
        (= (needs-resource affected1 medicine) 0)
        (= (needs-resource affected1 food) 10)
        (= (needs-resource affected1 water) 20)
        (= (needs-resource affected2 medicine) 40)
        (= (needs-resource affected2 food) 90)
        (= (needs-resource affected2 water) 10)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus0 affected2) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (evacuating bus1 affected2) 0)
        (= (evacuating bus2 affected0) 0)
        (= (evacuating bus2 affected1) 0)
        (= (evacuating bus2 affected2) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (contains truck2 medicine) 0)
        (= (contains truck2 food) 0)
        (= (contains truck2 water) 0)
        (= (capacity bus0) 100)
        (= (capacity bus1) 60)
        (= (capacity bus2) 40)
        (= (capacity truck0) 250)
        (= (capacity truck1) 250)
        (= (capacity truck2) 50)
        (= (distance safe0 affected0) 420)
        (= (distance affected0 safe0) 420)
        (= (distance safe0 affected1) 30)
        (= (distance affected1 safe0) 30)
        (= (distance safe0 affected2) 150)
        (= (distance affected2 safe0) 150)
        (= (distance affected0 affected1) 210)
        (= (distance affected1 affected0) 210)
        (= (distance affected0 affected2) 250)
        (= (distance affected2 affected0) 250)
        (= (distance affected1 affected2) 170)
        (= (distance affected2 affected1) 170)
        (= (per-unit-distance-cost bus0) 40)
        (= (per-unit-distance-cost bus1) 30)
        (= (per-unit-distance-cost bus2) 40)
        (= (per-unit-distance-cost truck0) 40)
        (= (per-unit-distance-cost truck1) 20)
        (= (per-unit-distance-cost truck2) 50)
        (= (per-unit-distance-time bus0) 4)
        (= (per-unit-distance-time bus1) 4)
        (= (per-unit-distance-time bus2) 1)
        (= (per-unit-distance-time truck0) 2)
        (= (per-unit-distance-time truck1) 9)
        (= (per-unit-distance-time truck2) 10)
        (= (per-unit-distribution-cost medicine) 7)
        (= (per-unit-distribution-cost food) 5)
        (= (per-unit-distribution-cost water) 8)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected0))
            (not (needs-evacuation affected1))
            (not (needs-evacuation affected2))
            (not (needs-medical-support affected0))
            (not (needs-medical-support affected1))
            (not (needs-rescue affected1))
            (not (needs-rescue affected2))
            (not (needs-rescue affected0))
            (= (person-to-evacuate affected0) 0)
            (= (person-to-evacuate affected1) 0)
            (= (person-to-evacuate affected2) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (needs-resource affected2 medicine) 0)
            (= (needs-resource affected2 food) 0)
            (= (needs-resource affected2 water) 0)
            (= (capacity bus0) 100)
            (= (capacity bus1) 60)
            (= (capacity bus2) 40)
            (= (capacity truck0) 250)
            (= (capacity truck1) 250)
            (= (capacity truck2) 50)
            (at truck0 safe0)
            (at truck1 safe0)
            (at truck2 safe0)
            (at bus0 safe0)
            (at bus1 safe0)
            (at bus2 safe0)
            (at medics0 safe0)
            (at medics1 safe0)
            (at rescuers0 safe0)
            (at rescuers1 safe0)
        )
    )
)
