(define (problem rapid-instance-8)
        (:domain rapid)
        
    (:objects
        safe0 - safe-location
        affected0 affected1 affected2 - affected-location
        medics0 - medical-support-team
        rescuers0 - rescue-team
        truck0 truck1 - freight-vehicle
        bus0 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe0)
        (at bus0 safe0)
        (at medics0 safe0)
        (at rescuers0 safe0)
        (needs-rescue affected0)
        (needs-rescue affected1)
        (needs-medical-support affected2)
        (needs-medical-support affected1)
        (needs-evacuation affected2)
        (= (person-to-evacuate affected2) 120)
        (= (priority affected0) 5)
        (= (priority affected1) 2)
        (= (priority affected2) 4)
        (= (team-size medics0) 20)
        (= (team-size rescuers0) 15)
        (= (stock safe0 medicine) 900)
        (= (stock safe0 food) 600)
        (= (stock safe0 water) 1800)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (stock affected2 medicine) 0)
        (= (stock affected2 food) 0)
        (= (stock affected2 water) 0)
        (= (needs-resource affected0 medicine) 60)
        (= (needs-resource affected0 food) 60)
        (= (needs-resource affected0 water) 70)
        (= (needs-resource affected1 medicine) 10)
        (= (needs-resource affected1 food) 40)
        (= (needs-resource affected1 water) 0)
        (= (needs-resource affected2 medicine) 100)
        (= (needs-resource affected2 food) 40)
        (= (needs-resource affected2 water) 90)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus0 affected2) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (capacity bus0) 20)
        (= (capacity truck0) 250)
        (= (capacity truck1) 100)
        (= (distance safe0 affected0) 20)
        (= (distance affected0 safe0) 20)
        (= (distance safe0 affected1) 250)
        (= (distance affected1 safe0) 250)
        (= (distance safe0 affected2) 300)
        (= (distance affected2 safe0) 300)
        (= (distance affected0 affected1) 360)
        (= (distance affected1 affected0) 360)
        (= (distance affected0 affected2) 350)
        (= (distance affected2 affected0) 350)
        (= (distance affected1 affected2) 240)
        (= (distance affected2 affected1) 240)
        (= (per-unit-distance-cost bus0) 30)
        (= (per-unit-distance-cost truck0) 40)
        (= (per-unit-distance-cost truck1) 20)
        (= (per-unit-distance-time bus0) 5)
        (= (per-unit-distance-time truck0) 4)
        (= (per-unit-distance-time truck1) 9)
        (= (per-unit-distribution-cost medicine) 4)
        (= (per-unit-distribution-cost food) 3)
        (= (per-unit-distribution-cost water) 1)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected2))
            (not (needs-medical-support affected2))
            (not (needs-medical-support affected1))
            (not (needs-rescue affected0))
            (not (needs-rescue affected1))
            (= (person-to-evacuate affected2) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (needs-resource affected2 medicine) 0)
            (= (needs-resource affected2 food) 0)
            (= (needs-resource affected2 water) 0)
            (= (capacity bus0) 20)
            (= (capacity truck0) 250)
            (= (capacity truck1) 100)
            (at truck0 safe0)
            (at truck1 safe0)
            (at bus0 safe0)
            (at medics0 safe0)
            (at rescuers0 safe0)
        )
    )
)
