(define (problem rapid-instance-14)
        (:domain rapid)
        
    (:objects
        safe0 - safe-location
        affected0 affected1 affected2 - affected-location
        medics0 medics1 - medical-support-team
        rescuers0 rescuers1 - rescue-team
        truck0 truck1 truck2 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe0)
        (at truck2 safe0)
        (at bus0 safe0)
        (at bus1 safe0)
        (at medics0 safe0)
        (at medics1 safe0)
        (at rescuers0 safe0)
        (at rescuers1 safe0)
        (needs-rescue affected1)
        (needs-rescue affected2)
        (needs-rescue affected0)
        (needs-medical-support affected1)
        (needs-medical-support affected2)
        (needs-evacuation affected1)
        (needs-evacuation affected0)
        (needs-evacuation affected2)
        (= (person-to-evacuate affected1) 170)
        (= (person-to-evacuate affected0) 70)
        (= (person-to-evacuate affected2) 180)
        (= (priority affected0) 2)
        (= (priority affected1) 3)
        (= (priority affected2) 4)
        (= (team-size medics0) 20)
        (= (team-size medics1) 10)
        (= (team-size rescuers0) 20)
        (= (team-size rescuers1) 25)
        (= (stock safe0 medicine) 300)
        (= (stock safe0 food) 1500)
        (= (stock safe0 water) 1800)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (stock affected2 medicine) 0)
        (= (stock affected2 food) 0)
        (= (stock affected2 water) 0)
        (= (needs-resource affected0 medicine) 0)
        (= (needs-resource affected0 food) 100)
        (= (needs-resource affected0 water) 40)
        (= (needs-resource affected1 medicine) 80)
        (= (needs-resource affected1 food) 30)
        (= (needs-resource affected1 water) 10)
        (= (needs-resource affected2 medicine) 40)
        (= (needs-resource affected2 food) 70)
        (= (needs-resource affected2 water) 100)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus0 affected2) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (evacuating bus1 affected2) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (contains truck2 medicine) 0)
        (= (contains truck2 food) 0)
        (= (contains truck2 water) 0)
        (= (capacity bus0) 40)
        (= (capacity bus1) 60)
        (= (capacity truck0) 50)
        (= (capacity truck1) 50)
        (= (capacity truck2) 50)
        (= (distance safe0 affected0) 140)
        (= (distance affected0 safe0) 140)
        (= (distance safe0 affected1) 390)
        (= (distance affected1 safe0) 390)
        (= (distance safe0 affected2) 170)
        (= (distance affected2 safe0) 170)
        (= (distance affected0 affected1) 40)
        (= (distance affected1 affected0) 40)
        (= (distance affected0 affected2) 320)
        (= (distance affected2 affected0) 320)
        (= (distance affected1 affected2) 450)
        (= (distance affected2 affected1) 450)
        (= (per-unit-distance-cost bus0) 30)
        (= (per-unit-distance-cost bus1) 20)
        (= (per-unit-distance-cost truck0) 40)
        (= (per-unit-distance-cost truck1) 50)
        (= (per-unit-distance-cost truck2) 40)
        (= (per-unit-distance-time bus0) 6)
        (= (per-unit-distance-time bus1) 8)
        (= (per-unit-distance-time truck0) 6)
        (= (per-unit-distance-time truck1) 4)
        (= (per-unit-distance-time truck2) 8)
        (= (per-unit-distribution-cost medicine) 10)
        (= (per-unit-distribution-cost food) 2)
        (= (per-unit-distribution-cost water) 3)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected1))
            (not (needs-evacuation affected0))
            (not (needs-evacuation affected2))
            (not (needs-medical-support affected1))
            (not (needs-medical-support affected2))
            (not (needs-rescue affected1))
            (not (needs-rescue affected2))
            (not (needs-rescue affected0))
            (= (person-to-evacuate affected1) 0)
            (= (person-to-evacuate affected0) 0)
            (= (person-to-evacuate affected2) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (needs-resource affected2 medicine) 0)
            (= (needs-resource affected2 food) 0)
            (= (needs-resource affected2 water) 0)
            (= (capacity bus0) 40)
            (= (capacity bus1) 60)
            (= (capacity truck0) 50)
            (= (capacity truck1) 50)
            (= (capacity truck2) 50)
            (at truck0 safe0)
            (at truck1 safe0)
            (at truck2 safe0)
            (at bus0 safe0)
            (at bus1 safe0)
            (at medics0 safe0)
            (at medics1 safe0)
            (at rescuers0 safe0)
            (at rescuers1 safe0)
        )
    )
)
