(define (problem rapid-instance-4)
        (:domain rapid)
        
    (:objects
        safe0 - safe-location
        affected0 affected1 - affected-location
        medics0 - medical-support-team
        rescuers0 - rescue-team
        truck0 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at bus0 safe0)
        (at bus1 safe0)
        (at medics0 safe0)
        (at rescuers0 safe0)
        (needs-rescue affected0)
        (needs-medical-support affected1)
        (needs-evacuation affected1)
        (= (person-to-evacuate affected1) 130)
        (= (priority affected0) 2)
        (= (priority affected1) 1)
        (= (team-size medics0) 10)
        (= (team-size rescuers0) 10)
        (= (stock safe0 medicine) 1600)
        (= (stock safe0 food) 2000)
        (= (stock safe0 water) 1200)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (needs-resource affected0 medicine) 20)
        (= (needs-resource affected0 food) 70)
        (= (needs-resource affected0 water) 0)
        (= (needs-resource affected1 medicine) 30)
        (= (needs-resource affected1 food) 40)
        (= (needs-resource affected1 water) 80)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (capacity bus0) 20)
        (= (capacity bus1) 50)
        (= (capacity truck0) 100)
        (= (distance safe0 affected0) 80)
        (= (distance affected0 safe0) 80)
        (= (distance safe0 affected1) 450)
        (= (distance affected1 safe0) 450)
        (= (distance affected0 affected1) 440)
        (= (distance affected1 affected0) 440)
        (= (per-unit-distance-cost bus0) 20)
        (= (per-unit-distance-cost bus1) 40)
        (= (per-unit-distance-cost truck0) 30)
        (= (per-unit-distance-time bus0) 1)
        (= (per-unit-distance-time bus1) 1)
        (= (per-unit-distance-time truck0) 4)
        (= (per-unit-distribution-cost medicine) 1)
        (= (per-unit-distribution-cost food) 4)
        (= (per-unit-distribution-cost water) 8)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected1))
            (not (needs-medical-support affected1))
            (not (needs-rescue affected0))
            (= (person-to-evacuate affected1) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (capacity bus0) 20)
            (= (capacity bus1) 50)
            (= (capacity truck0) 100)
            (at truck0 safe0)
            (at bus0 safe0)
            (at bus1 safe0)
            (at medics0 safe0)
            (at rescuers0 safe0)
        )
    )
)
