(define (problem rapid-instance-25)
        (:domain rapid)
        
    (:objects
        safe0 safe1 - safe-location
        affected0 affected1 affected2 affected3 affected4 - affected-location
        medics0 medics1 medics2 - medical-support-team
        rescuers0 rescuers1 rescuers2 - rescue-team
        truck0 truck1 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe1)
        (at bus0 safe1)
        (at bus1 safe0)
        (at medics0 safe0)
        (at medics1 safe0)
        (at medics2 safe0)
        (at rescuers0 safe0)
        (at rescuers1 safe1)
        (at rescuers2 safe1)
        (needs-rescue affected0)
        (needs-rescue affected3)
        (needs-rescue affected1)
        (needs-medical-support affected3)
        (needs-medical-support affected1)
        (needs-medical-support affected4)
        (needs-evacuation affected3)
        (needs-evacuation affected0)
        (needs-evacuation affected2)
        (= (person-to-evacuate affected3) 130)
        (= (person-to-evacuate affected0) 40)
        (= (person-to-evacuate affected2) 120)
        (= (priority affected0) 8)
        (= (priority affected1) 7)
        (= (priority affected2) 4)
        (= (priority affected3) 5)
        (= (priority affected4) 1)
        (= (team-size medics0) 10)
        (= (team-size medics1) 25)
        (= (team-size medics2) 10)
        (= (team-size rescuers0) 15)
        (= (team-size rescuers1) 10)
        (= (team-size rescuers2) 15)
        (= (stock safe0 medicine) 1500)
        (= (stock safe0 food) 1500)
        (= (stock safe0 water) 0)
        (= (stock safe1 medicine) 4000)
        (= (stock safe1 food) 1000)
        (= (stock safe1 water) 2000)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (stock affected2 medicine) 0)
        (= (stock affected2 food) 0)
        (= (stock affected2 water) 0)
        (= (stock affected3 medicine) 0)
        (= (stock affected3 food) 0)
        (= (stock affected3 water) 0)
        (= (stock affected4 medicine) 0)
        (= (stock affected4 food) 0)
        (= (stock affected4 water) 0)
        (= (needs-resource affected0 medicine) 100)
        (= (needs-resource affected0 food) 40)
        (= (needs-resource affected0 water) 10)
        (= (needs-resource affected1 medicine) 80)
        (= (needs-resource affected1 food) 80)
        (= (needs-resource affected1 water) 40)
        (= (needs-resource affected2 medicine) 40)
        (= (needs-resource affected2 food) 90)
        (= (needs-resource affected2 water) 20)
        (= (needs-resource affected3 medicine) 40)
        (= (needs-resource affected3 food) 70)
        (= (needs-resource affected3 water) 90)
        (= (needs-resource affected4 medicine) 40)
        (= (needs-resource affected4 food) 0)
        (= (needs-resource affected4 water) 90)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus0 affected2) 0)
        (= (evacuating bus0 affected3) 0)
        (= (evacuating bus0 affected4) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (evacuating bus1 affected2) 0)
        (= (evacuating bus1 affected3) 0)
        (= (evacuating bus1 affected4) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (capacity bus0) 80)
        (= (capacity bus1) 80)
        (= (capacity truck0) 50)
        (= (capacity truck1) 250)
        (= (distance safe0 safe1) 420)
        (= (distance safe1 safe0) 420)
        (= (distance safe0 affected0) 340)
        (= (distance affected0 safe0) 340)
        (= (distance safe0 affected1) 330)
        (= (distance affected1 safe0) 330)
        (= (distance safe0 affected2) 170)
        (= (distance affected2 safe0) 170)
        (= (distance safe0 affected3) 380)
        (= (distance affected3 safe0) 380)
        (= (distance safe0 affected4) 320)
        (= (distance affected4 safe0) 320)
        (= (distance safe1 affected0) 140)
        (= (distance affected0 safe1) 140)
        (= (distance safe1 affected1) 70)
        (= (distance affected1 safe1) 70)
        (= (distance safe1 affected2) 140)
        (= (distance affected2 safe1) 140)
        (= (distance safe1 affected3) 150)
        (= (distance affected3 safe1) 150)
        (= (distance safe1 affected4) 430)
        (= (distance affected4 safe1) 430)
        (= (distance affected0 affected1) 420)
        (= (distance affected1 affected0) 420)
        (= (distance affected0 affected2) 180)
        (= (distance affected2 affected0) 180)
        (= (distance affected0 affected3) 90)
        (= (distance affected3 affected0) 90)
        (= (distance affected0 affected4) 420)
        (= (distance affected4 affected0) 420)
        (= (distance affected1 affected2) 440)
        (= (distance affected2 affected1) 440)
        (= (distance affected1 affected3) 280)
        (= (distance affected3 affected1) 280)
        (= (distance affected1 affected4) 170)
        (= (distance affected4 affected1) 170)
        (= (distance affected2 affected3) 250)
        (= (distance affected3 affected2) 250)
        (= (distance affected2 affected4) 60)
        (= (distance affected4 affected2) 60)
        (= (distance affected3 affected4) 340)
        (= (distance affected4 affected3) 340)
        (= (per-unit-distance-cost bus0) 30)
        (= (per-unit-distance-cost bus1) 30)
        (= (per-unit-distance-cost truck0) 30)
        (= (per-unit-distance-cost truck1) 50)
        (= (per-unit-distance-time bus0) 3)
        (= (per-unit-distance-time bus1) 5)
        (= (per-unit-distance-time truck0) 4)
        (= (per-unit-distance-time truck1) 2)
        (= (per-unit-distribution-cost medicine) 4)
        (= (per-unit-distribution-cost food) 7)
        (= (per-unit-distribution-cost water) 3)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected3))
            (not (needs-evacuation affected0))
            (not (needs-evacuation affected2))
            (not (needs-medical-support affected3))
            (not (needs-medical-support affected1))
            (not (needs-medical-support affected4))
            (not (needs-rescue affected0))
            (not (needs-rescue affected3))
            (not (needs-rescue affected1))
            (= (person-to-evacuate affected3) 0)
            (= (person-to-evacuate affected0) 0)
            (= (person-to-evacuate affected2) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (needs-resource affected2 medicine) 0)
            (= (needs-resource affected2 food) 0)
            (= (needs-resource affected2 water) 0)
            (= (needs-resource affected3 medicine) 0)
            (= (needs-resource affected3 food) 0)
            (= (needs-resource affected3 water) 0)
            (= (needs-resource affected4 medicine) 0)
            (= (needs-resource affected4 food) 0)
            (= (needs-resource affected4 water) 0)
            (= (capacity bus0) 80)
            (= (capacity bus1) 80)
            (= (capacity truck0) 50)
            (= (capacity truck1) 250)
            (at truck0 safe0)
            (at truck1 safe1)
            (at bus0 safe1)
            (at bus1 safe0)
            (at medics0 safe0)
            (at medics1 safe0)
            (at medics2 safe0)
            (at rescuers0 safe0)
            (at rescuers1 safe1)
            (at rescuers2 safe1)
        )
    )
)
