(define (problem rapid-instance-2)
        (:domain rapid)
        
    (:objects
        safe0 - safe-location
        affected0 affected1 - affected-location
        medics0 medics1 - medical-support-team
        rescuers0 rescuers1 - rescue-team
        truck0 - freight-vehicle
        bus0 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at bus0 safe0)
        (at medics0 safe0)
        (at medics1 safe0)
        (at rescuers0 safe0)
        (at rescuers1 safe0)
        (needs-rescue affected0)
        (needs-medical-support affected0)
        (needs-evacuation affected1)
        (= (person-to-evacuate affected1) 70)
        (= (priority affected0) 1)
        (= (priority affected1) 3)
        (= (team-size medics0) 15)
        (= (team-size medics1) 10)
        (= (team-size rescuers0) 25)
        (= (team-size rescuers1) 15)
        (= (stock safe0 medicine) 1200)
        (= (stock safe0 food) 800)
        (= (stock safe0 water) 1200)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (needs-resource affected0 medicine) 70)
        (= (needs-resource affected0 food) 10)
        (= (needs-resource affected0 water) 100)
        (= (needs-resource affected1 medicine) 60)
        (= (needs-resource affected1 food) 90)
        (= (needs-resource affected1 water) 40)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (capacity bus0) 80)
        (= (capacity truck0) 100)
        (= (distance safe0 affected0) 490)
        (= (distance affected0 safe0) 490)
        (= (distance safe0 affected1) 60)
        (= (distance affected1 safe0) 60)
        (= (distance affected0 affected1) 190)
        (= (distance affected1 affected0) 190)
        (= (per-unit-distance-cost bus0) 20)
        (= (per-unit-distance-cost truck0) 40)
        (= (per-unit-distance-time bus0) 9)
        (= (per-unit-distance-time truck0) 9)
        (= (per-unit-distribution-cost medicine) 8)
        (= (per-unit-distribution-cost food) 4)
        (= (per-unit-distribution-cost water) 4)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected1))
            (not (needs-medical-support affected0))
            (not (needs-rescue affected0))
            (= (person-to-evacuate affected1) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (capacity bus0) 80)
            (= (capacity truck0) 100)
            (at truck0 safe0)
            (at bus0 safe0)
            (at medics0 safe0)
            (at medics1 safe0)
            (at rescuers0 safe0)
            (at rescuers1 safe0)
        )
    )
)
