(define (problem rapid-instance-18)
        (:domain rapid)
        
    (:objects
        safe0 safe1 - safe-location
        affected0 affected1 - affected-location
        medics0 medics1 - medical-support-team
        rescuers0 rescuers1 - rescue-team
        truck0 truck1 - freight-vehicle
        bus0 bus1 - transit-vehicle
        medicine food water - resource
    )
    (:init
        (at truck0 safe0)
        (at truck1 safe1)
        (at bus0 safe0)
        (at bus1 safe0)
        (at medics0 safe0)
        (at medics1 safe1)
        (at rescuers0 safe1)
        (at rescuers1 safe1)
        (needs-rescue affected0)
        (needs-rescue affected1)
        (needs-medical-support affected1)
        (needs-medical-support affected0)
        (needs-evacuation affected1)
        (needs-evacuation affected0)
        (= (person-to-evacuate affected1) 20)
        (= (person-to-evacuate affected0) 70)
        (= (priority affected0) 1)
        (= (priority affected1) 2)
        (= (team-size medics0) 25)
        (= (team-size medics1) 25)
        (= (team-size rescuers0) 25)
        (= (team-size rescuers1) 15)
        (= (stock safe1 medicine) 800)
        (= (stock safe1 food) 1200)
        (= (stock safe1 water) 1400)
        (= (stock safe0 medicine) 0)
        (= (stock safe0 food) 0)
        (= (stock safe0 water) 0)
        (= (stock affected0 medicine) 0)
        (= (stock affected0 food) 0)
        (= (stock affected0 water) 0)
        (= (stock affected1 medicine) 0)
        (= (stock affected1 food) 0)
        (= (stock affected1 water) 0)
        (= (needs-resource affected0 medicine) 90)
        (= (needs-resource affected0 food) 80)
        (= (needs-resource affected0 water) 100)
        (= (needs-resource affected1 medicine) 30)
        (= (needs-resource affected1 food) 0)
        (= (needs-resource affected1 water) 20)
        (= (evacuating bus0 affected0) 0)
        (= (evacuating bus0 affected1) 0)
        (= (evacuating bus1 affected0) 0)
        (= (evacuating bus1 affected1) 0)
        (= (contains truck0 medicine) 0)
        (= (contains truck0 food) 0)
        (= (contains truck0 water) 0)
        (= (contains truck1 medicine) 0)
        (= (contains truck1 food) 0)
        (= (contains truck1 water) 0)
        (= (capacity bus0) 90)
        (= (capacity bus1) 90)
        (= (capacity truck0) 50)
        (= (capacity truck1) 100)
        (= (distance safe0 safe1) 500)
        (= (distance safe1 safe0) 500)
        (= (distance safe0 affected0) 170)
        (= (distance affected0 safe0) 170)
        (= (distance safe0 affected1) 290)
        (= (distance affected1 safe0) 290)
        (= (distance safe1 affected0) 240)
        (= (distance affected0 safe1) 240)
        (= (distance safe1 affected1) 120)
        (= (distance affected1 safe1) 120)
        (= (distance affected0 affected1) 110)
        (= (distance affected1 affected0) 110)
        (= (per-unit-distance-cost bus0) 50)
        (= (per-unit-distance-cost bus1) 50)
        (= (per-unit-distance-cost truck0) 50)
        (= (per-unit-distance-cost truck1) 20)
        (= (per-unit-distance-time bus0) 2)
        (= (per-unit-distance-time bus1) 8)
        (= (per-unit-distance-time truck0) 3)
        (= (per-unit-distance-time truck1) 7)
        (= (per-unit-distribution-cost medicine) 7)
        (= (per-unit-distribution-cost food) 9)
        (= (per-unit-distribution-cost water) 10)
        (= (total-cost) 0)
        (= (time) 0)
        (= (plan-length) 0)
    )
    (:goal
        (and
            (not (needs-evacuation affected1))
            (not (needs-evacuation affected0))
            (not (needs-medical-support affected1))
            (not (needs-medical-support affected0))
            (not (needs-rescue affected0))
            (not (needs-rescue affected1))
            (= (person-to-evacuate affected1) 0)
            (= (person-to-evacuate affected0) 0)
            (= (needs-resource affected0 medicine) 0)
            (= (needs-resource affected0 food) 0)
            (= (needs-resource affected0 water) 0)
            (= (needs-resource affected1 medicine) 0)
            (= (needs-resource affected1 food) 0)
            (= (needs-resource affected1 water) 0)
            (= (capacity bus0) 90)
            (= (capacity bus1) 90)
            (= (capacity truck0) 50)
            (= (capacity truck1) 100)
            (at truck0 safe0)
            (at truck1 safe1)
            (at bus0 safe0)
            (at bus1 safe0)
            (at medics0 safe0)
            (at medics1 safe1)
            (at rescuers0 safe1)
            (at rescuers1 safe1)
        )
    )
)
